name: Picastro - Main Domain (web) cPanel FTP

on:
  push:
    branches:
      - main
      - danyal

jobs:
  deploy-main:
    name: 🎉 Deploy Main Branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Condition to run only on 'main' branch
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: picastro.beckapps.co
          username: danyal@picastro.beckapps.co
          password: P6zdzy7#++g!
          timeout: 999999

  deploy-danyal:
    name: 🎉 Deploy Danyal Branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/danyal' # Condition to run only on 'danyal' branch
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: picastro.co.uk
          username: danyal@picastro.co.uk
          password: Zv*udPupLs9QD906
          timeout: 999999
